executable="${GW_HOME}/gw"
run_as_shell=true

[alias]
git="!git.sh \"$@\""
# Here are some aliases for git.
# There is no intent to reimplement all aliases here.
# Here are just a couple of most frequently used.
# You can call git command directly for all other cases.

# show current branch
cb = "!git.sh rev-parse --abbrev-ref HEAD"

# show branches
br = "!git.sh branch -v"
# highlight current branch (it is usefull to get one line output for each repository)
b1 = "!git.sh branch -v | grep --color '*'"

co = "!git.sh co \"$@\" | grep -A 1 '\\['"
sh="!execute-cmd.sh \"$@\""
